heat_template_version: 2013-05-23

description: Template for deploying a single server with predefined properties.

parameters:
  CDPLANE_net_name: {default: C/DPLANE_NET, description: Name of private network to be
      created, type: string}
  CDPLANE_net_cidr: {default: 10.10.1.0/24, description: Private network address (CIDR notation),type: string}
  CDPLANE_net_gateway: {default: 10.10.1.1, description: Private network gateway address,
    type: string}
  CDPLANE_net_pool_end: {default: 10.10.1.200, description: End of private network
      IP address allocation pool, type: string}
  CDPLANE_net_pool_start: {default: 10.10.1.100, description: Start of private network
      IP address allocation pool, type: string}
  NET_1_NAME: {default: NET_1_NET, description: Name of private network to be
      created, type: string}
  NET_1_CIDR: {default: 20.20.1.0/24, description: Private network address (CIDR notation),type: string}
  NET_1_GW: {default: 20.20.1.1, description: Private network gateway address,
    type: string}
  NET_1_POOL_END: {default: 20.20.1.200, description: End of private network
      IP address allocation pool, type: string}
  NET_1_POOL_START: {default: 20.20.1.100, description: Start of private network
      IP address allocation pool, type: string}
  NET_2_NAME: {default: NET_2_NET, description: Name of private network to be
      created, type: string}
  NET_2_CIDR: {default: 30.30.1.0/24, description: Private network address (CIDR notation),type: string}
  NET_2_GW: {default: 30.30.1.1, description: Private network gateway address,
    type: string}
  NET_2_POOL_END: {default: 30.30.1.200, description: End of private network
      IP address allocation pool, type: string}
  NET_2_POOL_START: {default: 30.30.1.100, description: Start of private network
      IP address allocation pool, type: string}
  NET_3_NAME: {default: NET_3_NET, description: Name of private network to be
      created, type: string}
  NET_3_CIDR: {default: 40.40.1.0/24, description: Private network address (CIDR notation),type: string}
  NET_3_GW: {default: 40.40.1.1, description: Private network gateway address,
    type: string}
  NET_3_POOL_END: {default: 40.40.1.200, description: End of private network
      IP address allocation pool, type: string}
  NET_3_POOL_START: {default: 40.40.1.100, description: Start of private network
      IP address allocation pool, type: string}
  NET_4_NAME: {default: NET_4_NET, description: Name of private network to be
      created, type: string}
  NET_4_CIDR: {default: 50.50.1.0/24, description: Private network address (CIDR notation),type: string}
  NET_4_GW: {default: 50.50.1.1, description: Private network gateway address,
    type: string}
  NET_4_POOL_END: {default: 50.50.1.200, description: End of private network
      IP address allocation pool, type: string}
  NET_4_POOL_START: {default: 50.50.1.100, description: Start of private network
      IP address allocation pool, type: string}
  PDN_net_name: {default: PDN_NET, description: Name of private network to be created,
    type: string}
  PDN_net_cidr: {default: 30.0.0.0/24, description: Private network address (CIDR
      notation), type: string}
  PDN_net_gateway: {default: 30.0.0.1, description: Private network gateway address,
    type: string}
  PDN_net_pool_end: {default: 30.0.0.200, description: End of private network IP address
      allocation pool, type: string}
  PDN_net_pool_start: {default: 30.0.0.100, description: Start of private network
      IP address allocation pool, type: string}
  SGI_net_name: {default: SGI_NET, description: Name of private network to be created,
    type: string}
  SGI_net_cidr: {default: 20.0.0.0/24, description: Private network address (CIDR
      notation), type: string}
  SGI_net_gateway: {default: 20.0.0.1, description: Private network gateway address,
    type: string}
  SGI_net_pool_end: {default: 20.0.0.200, description: End of private network IP address
      allocation pool, type: string}
  SGI_net_pool_start: {default: 20.0.0.100, description: Start of private network
      IP address allocation pool, type: string}
  UE_net_name: {default: UE_NET, description: Name of private network to be created, type: string}
  UE_net_cidr: {default: 10.10.0.0/24, description: Private network address (CIDR
      notation), type: string}
  UE_net_gateway: {default: 10.10.0.1, description: Private network gateway address,
    type: string}
  UE_net_pool_end: {default: 10.10.0.200, description: End of private network IP address
      allocation pool, type: string}
  UE_net_pool_start: {default: 10.10.0.100, description: Start of private network
      IP address allocation pool, type: string}
  flavor: {default: Small-Dedicated, description: Flavor to use for servers, type: string}
  image: {default: Ubuntu 14.04, description: Name of image to use for servers, type: string}
  flavor_small: {default: Small-Dedicated, description: Flavor to use for servers, type: string}
  public_net: {default: public0, description: 'ID or name of public network for which
      floating IP addresses will be allocated', type: string}
  SBPATH: {default: /home/ubuntu32/, type: string}
  SPATH: {default: /home/ubuntu32/, type: string}
  SAE_BIN_PATH: {default: /home/ubuntu32/,type: string}
  MME_BIN_PATH: {default: /home/ubuntu32/,type: string}
  public_net_id: {default: 99bcbc76-a202-4f99-a05a-b82e10891bc0,type: string}   
resources:
  NET_1_net:
    properties:
      name: {get_param: NET_1_NAME}
    type: OS::Neutron::Net
  NET_1_subnet:
    properties:
      allocation_pools:
      - end: {get_param: NET_1_POOL_END}
        start: {get_param: NET_1_POOL_START}
      cidr: {get_param: NET_1_CIDR}
      gateway_ip: {get_param: NET_1_GW}
      network_id: {get_resource: NET_1_net}
    type: OS::Neutron::Subnet
  NET_2_net:
    properties:
      name: {get_param: NET_2_NAME}
    type: OS::Neutron::Net
  NET_2_subnet:
    properties:
      allocation_pools:
      - end: {get_param: NET_2_POOL_END}
        start: {get_param: NET_2_POOL_START}
      cidr: {get_param: NET_2_CIDR}
      gateway_ip: {get_param: NET_2_GW}
      network_id: {get_resource: NET_2_net}
    type: OS::Neutron::Subnet
  NET_3_net:
    properties:
      name: {get_param: NET_3_NAME}
    type: OS::Neutron::Net
  NET_3_subnet:
    properties:
      allocation_pools:
      - end: {get_param: NET_3_POOL_END}
        start: {get_param: NET_3_POOL_START}
      cidr: {get_param: NET_3_CIDR}
      gateway_ip: {get_param: NET_3_GW}
      network_id: {get_resource: NET_3_net}
    type: OS::Neutron::Subnet
  NET_4_net:
    properties:
      name: {get_param: NET_4_NAME}
    type: OS::Neutron::Net
  NET_4_subnet:
    properties:
      allocation_pools:
      - end: {get_param: NET_4_POOL_END}
        start: {get_param: NET_4_POOL_START}
      cidr: {get_param: NET_4_CIDR}
      gateway_ip: {get_param: NET_4_GW}
      network_id: {get_resource: NET_4_net}
    type: OS::Neutron::Subnet  
  UE_net:
    properties:
      name: {get_param: UE_net_name}
    type: OS::Neutron::Net
  UE_subnet:
    properties:
      allocation_pools:
      - end: {get_param: UE_net_pool_end}
        start: {get_param: UE_net_pool_start}
      cidr: {get_param: UE_net_cidr}
      gateway_ip: {get_param: UE_net_gateway}
      network_id: {get_resource: UE_net}
    type: OS::Neutron::Subnet
  PDN_net:
    properties:
      name: {get_param: PDN_net_name}
    type: OS::Neutron::Net
  PDN_subnet:
    properties:
      allocation_pools:
      - end: {get_param: PDN_net_pool_end}
        start: {get_param: PDN_net_pool_start}
      cidr: {get_param: PDN_net_cidr}
      gateway_ip: {get_param: PDN_net_gateway}
      network_id: {get_resource: PDN_net}
    type: OS::Neutron::Subnet
  router:
    properties:
      external_gateway_info:
        network: {get_param: public_net}
    type: OS::Neutron::Router
  router_interface:
    properties:
      router_id: {get_resource: router}
      subnet_id: {get_resource: PDN_subnet}
    type: OS::Neutron::RouterInterface
  PDN_port1:
    properties:
      fixed_ips: 
      - ip_address: 30.0.0.108
        subnet_id: {get_resource: PDN_subnet}
      network_id: {get_resource: PDN_net}
    type: OS::Neutron::Port
  PDN_port2:
    properties:
      fixed_ips: 
      - ip_address: 50.50.1.107
        subnet_id: {get_resource: NET_4_subnet}
      network_id: {get_resource: NET_4_net}
    type: OS::Neutron::Port
  SAE_port1:
    properties:
      
      fixed_ips: 
      - ip_address: 30.0.0.107
        subnet_id: {get_resource: PDN_subnet}
      network_id: {get_resource: PDN_net}
    type: OS::Neutron::Port
  floating_ip1:
    properties:
      floating_network_id: {get_param: public_net_id}
      port_id: {get_resource: SAE_port1}
    type: OS::Neutron::FloatingIP 
  SAE_port2:
    properties:
      fixed_ips: 
      - ip_address: 20.20.1.104
        subnet_id: {get_resource: NET_1_subnet}
      network_id: {get_resource: NET_1_net}
    type: OS::Neutron::Port
  SAE_port3:
    properties:
      fixed_ips: 
      - ip_address: 30.30.1.107
        subnet_id: {get_resource: NET_2_subnet}
      network_id: {get_resource: NET_2_net}
    type: OS::Neutron::Port
  SAE_port4:
    properties:
      fixed_ips: 
      - ip_address: 40.40.1.109
        subnet_id: {get_resource: NET_3_subnet}
      network_id: {get_resource: NET_3_net}
    type: OS::Neutron::Port
  SAE_port5:
    properties:
      fixed_ips: 
      - ip_address: 50.50.1.106
        subnet_id: {get_resource: NET_4_subnet}
      network_id: {get_resource: NET_4_net}
    type: OS::Neutron::Port
  UE_port1:
    properties:
      fixed_ips:
      - ip_address: 10.10.0.254
        subnet_id: {get_resource: UE_subnet}
      network_id: {get_resource: UE_net}
    type: OS::Neutron::Port
  MME_port1:
    properties:
      fixed_ips: 
      - ip_address: 30.0.0.110
        subnet_id: {get_resource: PDN_subnet}
      network_id: {get_resource: PDN_net}
    type: OS::Neutron::Port
  floating_ip2:
    properties:
      floating_network_id: {get_param: public_net_id}
      port_id: {get_resource: MME_port1}
    type: OS::Neutron::FloatingIP
  MME_port2:
    properties:
      fixed_ips: 
      - ip_address: 10.10.0.110
        subnet_id: {get_resource: UE_subnet}
      network_id: {get_resource: UE_net}
    type: OS::Neutron::Port
  MME_port3:
    properties:
      fixed_ips: 
      - ip_address: 20.20.1.101
        subnet_id: {get_resource: NET_1_subnet}
      network_id: {get_resource: NET_1_net}
    type: OS::Neutron::Port
#  MME_port3:
#    properties:
#      fixed_ips: 
#      - ip_address: 30.30.1.106
#        subnet_id: {get_resource: NET_2_subnet}
#      network_id: {get_resource: NET_2_net}
#    type: OS::Neutron::Port
  vMME:
    properties:
      flavor: {get_param: flavor}
      image: {get_param: image}
      name: vMME
      networks:
      - port: {get_resource: MME_port1}
      - port: {get_resource: MME_port2}
      - port: {get_resource: MME_port3}
#      - port: {get_resource: MME_port4}            
    type: OS::Nova::Server
  vSAE:
    properties:
      flavor: {get_param: flavor}
      image: {get_param: image}
      name: vSAE
      networks:
      - port: {get_resource: SAE_port1}
      - port: {get_resource: SAE_port2}
      - port: {get_resource: SAE_port3}
      - port: {get_resource: SAE_port4}
      - port: {get_resource: SAE_port5}
      user_data:
        str_replace:
          params:
            $ccidr: {get_param: CDPLANE_net_cidr}
            $cgateway: {get_param: CDPLANE_net_gateway}
            $host0:
              get_attr: [SAE_port1, fixed_ips, 0, ip_address]
            $host1:
              get_attr: [SAE_port2, fixed_ips, 0, ip_address]
            $host2:
              get_attr: [SAE_port3, fixed_ips, 0, ip_address]
            $host3:
              get_attr: [SAE_port4, fixed_ips, 0, ip_address]
            $host4:
              get_attr: [SAE_port5, fixed_ips, 0, ip_address]
            $sbpath: {get_param: SBPATH}
            $scidr: {get_param: SGI_net_cidr}
            $spath: {get_param: SPATH}
          template: "#cloud-config\nhostname: SAE\nfqdn: SAE\nmanage_etc_hosts:: true\n\
          runcmd:\n - sudo su\n - cd /home/ubuntu32\n - ./nwLteSaeGw --gtpu-ip $host1 --sgw-s11-ip $host1 --sgw-s5-ip $host3 --pgw-s5-ip $host2 --sgi-if eth0 --ippool-subnet 10.10.0.0 --ippool-mask 255.255.255.0 | tee /home/ubuntu32/SGW_OUTPUT_file.txt"
    type: OS::Nova::Server
  vUE:
    properties:
      flavor: {get_param: flavor_small}
      image: {get_param: image}
      name: vUE
      networks:
      - port: {get_resource: UE_port1}
    type: OS::Nova::Server
  vPDN:
    properties:
      flavor: {get_param: flavor_small}
      image: {get_param: image}
      name: vPDN
      networks:
      - port: {get_resource: PDN_port1}
      - port: {get_resource: PDN_port2}
    type: OS::Nova::Server
